apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: ec2-test
spec:
  forProvider:
    ami: ami-dummy
    instanceType: t3.micro
    region: us-east-1
  providerConfigRef:
    name: default
